name: brillenfux
description: my views on ...
url: https://mvo.brillenfux.com

defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
permalink: /:title/
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

gems:
  - jekyll-sitemap
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - TODO.md
  - CNAME
